return {
    units = {
        "npc_dota_hero_nevermore",
        "npc_dota_hero_shadow_demon",
        "npc_dota_hero_earthshaker",
        "npc_dota_hero_oracle",
        "npc_dota_hero_abyssal_underlord",
        "npc_dota_hero_grimstroke",
        "npc_dota_hero_beastmaster",
        "npc_dota_hero_sniper",
        "npc_dota_hero_brewmaster",

        "npc_dota_hero_sanya_towel_master",
        "npc_dota_hero_sanya_rapper",
        "npc_dota_hero_sanya_logarithmus",
        "npc_dota_hero_sanya",
        "npc_dota_hero_sanya_ending",

        "npc_subway_city",
        "npc_subway_to_city",
        "npc_subway_fake",
        "npc_flask_barrel",
        "npc_derek_keyhole",

        "npc_training_dummy",
        "npc_minigame_barrel",

        "npc_courier_knight",
        "npc_courier_bug",
        "npc_courier_alkash",
        "npc_courier_pivo",
        "npc_courier_chicken",
        "npc_courier_carpet",
        "npc_courier_pudge",
        "npc_courier_hamster",
        "npc_courier_koala",
        "npc_courier_shop",
        "npc_courier_cat",
        "npc_courier_drone",
        "npc_courier_donkeys",
        "npc_courier_bh",
        "npc_courier_chest",
        "npc_courier_skeleton",
        "npc_courier_crocodile",
        "npc_courier_sniffer",
        "npc_courier_smart",

        "npc_courier_tomato",
        "npc_courier_psycho",
        "npc_courier_gardener",
        "npc_courier_ant",
        "npc_courier_garden_dog",

        "npc_courier_roshanchik",
        "npc_courier_bober",
        "npc_courier_rabbit",
        "npc_courier_boar",
        "npc_courier_raccoon",
        "npc_courier_parrot",
        "npc_courier_mushroom_1",
        "npc_courier_mushroom_2",
        "npc_courier_mushroom_3",
        "npc_courier_muhomor",
        "npc_courier_plant",
        "npc_courier_octopus_1",
        "npc_courier_octopus_2",
        "npc_courier_purple",
        "npc_courier_sea_horse",
        "npc_courier_turtle",
        "npc_courier_crab",
        "npc_courier_axolotl",
        "npc_courier_navi",
        "npc_courier_cripple_dog",
        "npc_courier_demon",
        "npc_courier_evil_shop",
        "npc_courier_statue",
        "npc_courier_bones",
        "npc_courier_babka_2",
        "npc_courier_blue_frog",
        "npc_courier_pig",
        "npc_courier_winter_cat",
        "npc_courier_furion",

        "npc_courier_aghanim",
        "npc_courier_grandpa",
        "npc_courier_gold_hamster",
        "npc_courier_gold_cat",
        "npc_courier_gold_wizard",
        "npc_courier_blue_zombie",
        "npc_courier_taksa",
        "npc_courier_demon_book",
        "npc_courier_gold_dp",
        "npc_courier_black_wizard",
        "npc_courier_pudge_dog",
        "npc_courier_doom",

        "npc_tormentor",
        "npc_shamanka",
        "npc_gate_troll_uruk",
        "npc_gate_troll_biruk",
        "npc_gate_troll_diruk",
        "npc_guide",
        "npc_creep_bob",
        "npc_creep_rogach",
        "npc_mustache",
        "npc_monkey_king",
        "npc_monkey_king_summon",
        "npc_blue_prince",
        "npc_blue_prince",
        "npc_ogre_magi",
        "npc_ogre_bruiser",
        "npc_brewmaster",
        "npc_rape_victim",
        "npc_predvestnik",
        "npc_mystery",
        "npc_templar_assasin",
        "npc_alchemist",
        "npc_scientist",
        "npc_red",
        "npc_gorilla",
        "npc_goden",
        "npc_goden_summon",
        "npc_ball",
        "npc_chaser",
        "npc_cat_barrel",
        "npc_island_guard",
        "npc_island_fiend",
        "npc_island_demon",
        "npc_bomb_place",
        "npc_bomb",
        "npc_killer",

        "npc_storyteller",
        "npc_wasteland",
        "npc_leader",
        "npc_xavier",
        "npc_concert_guard",
        "npc_dream",
        "npc_dream_golden",
        "npc_hermit",
        "npc_green",
        "npc_perekup",
        "npc_genius",
        "npc_ghetto_ranged",
        "npc_ghetto_melee",
        "npc_concert_lina",
        "npc_concert_legion",
        "npc_concert_meepo",
        "npc_concert_wk",
        "npc_gangster",
        "npc_blue",

        "npc_derek",
        "npc_george",
        "npc_george_summon",

        "towel_summon",

        "npc_shooter",
        "npc_clash_creep_radiant",
        "npc_clash_creep_dire",
        "npc_clash_creep_dire_ranged",
        "npc_clash_creep_radiant_ranged",
        "npc_clash_creep_mega_sanya_1",
        "npc_clash_creep_mega_sanya_2",
        "npc_dota_custom_tower_bad",
        "npc_dota_custom_tower_good",
        "npc_dota_custom_king_tower_bad",
        "npc_dota_custom_king_tower_good",

        -- dota units
        "npc_dota_hero_venomancer",
        "npc_dota_hero_axe",
        "npc_dota_hero_razor",
        "npc_dota_hero_antimage",
        "npc_dota_hero_monkey_king",
        "npc_dota_roshan",
        "npc_dota_hero_techies",
        "npc_dota_hero_furion",
        "npc_dota_hero_meepo",
        "npc_dota_hero_nyx_assassin",
        "npc_dota_neutral_gnoll_assassin",
        "npc_dota_neutral_polar_furbolg_ursa_warrior",
        "npc_dota_neutral_ice_shaman",
        "npc_dota_hero_lich",
        "npc_dota_neutral_ogre_mauler",
        "npc_dota_neutral_alpha_wolf",
        "npc_dota_neutral_dark_troll_warlord",
        "npc_dota_hero_undying",
        "npc_dota_hero_treant",
        "npc_dota_hero_tiny",
        "npc_dota_hero_lion",
        "npc_dota_hero_tusk",
        "npc_dota_hero_invoker",
        "npc_dota_hero_zuus",
        "npc_dota_hero_crystal_maiden",
        "npc_dota_necronomicon_archer_1",
        "npc_dota_hero_rattletrap",
        "npc_dota_neutral_warpine_raider",
        "npc_dota_hero_jakiro",
        "npc_dota_hero_ancient_apparition",
        "npc_dota_hero_tidehunter",
        "npc_dota_hero_slardar",
        "npc_dota_hero_morphling",
        "npc_dota_hero_slark",
        "npc_dota_hero_abaddon",
        "npc_dota_hero_life_stealer",
        "npc_dota_hero_sand_king",
        "npc_dota_hero_drow_ranger",
        "npc_dota_hero_ursa",
        "npc_dota_hero_elder_titan",
        "npc_dota_hero_pudge",
        "npc_dota_hero_pugna",
        "npc_dota_greevil",
        "npc_dota_hero_earthshaker",
        "npc_dota_furion_treant",
        "npc_dota_hero_nyx_assassin",
        "npc_dota_hero_viper",
        "npc_dota_hero_life_stealer",
        "npc_dota_hero_huskar",
        "npc_dota_hero_troll_warlord",
        "npc_dota_hero_legion_commander",
        "npc_dota_hero_mars",
        "npc_dota_hero_chaos_knight",



        -- jungle
        "npc_jungle_venomancer",
        "npc_dota_venomancer_plague_ward_1",
        "npc_dota_venomancer_plague_ward_2",
        "npc_dota_venomancer_plague_ward_3",
        "npc_dota_venomancer_plague_ward_4",
        "npc_jungle_creep_melee",
        "npc_jungle_creep_range",
        "npc_jungle_axe",
        "npc_jungle_sisipisi",
        "npc_jungle_roshan",
        "npc_jungle_miniroshan",
        "npc_jungle_techies_1",
        "npc_jungle_techies_2",
        "npc_jungle_techies_3",
        "npc_jungle_shroom_melee",
        "npc_jungle_shroom_ranged",
        "npc_jungle_shroom_furion",
        "npc_jungle_gnoll",
        "npc_jungle_ancdragon",
        "npc_jungle_pomidorko",
        "npc_jungle_icebear",
        "npc_jungle_bufferbear",
        "npc_jungle_apple_melee",
        "npc_jungle_apple_ranged",
        "npc_jungle_perdun",
        "npc_jungle_perdun_flower",

        -- ocean
        "npc_ocean_creep_range",
        "npc_ocean_siege",
        "npc_ocean_tusik_mini_a",
        "npc_ocean_tusik_mini_b_1",
        "npc_ocean_tusik_mini_b_2",
        "npc_ocean_tusik_papa",
        "npc_ocean_tadpole_ranged_1",
        "npc_ocean_tadpole_ranged_2",
        "npc_ocean_tadpole_ranged_3",
        "npc_ocean_tadpole_big_melee",
        "npc_ocean_tadpole_big_range_1",
        "npc_ocean_tadpole_big_range_2",
        "npc_ocean_spider_fire",
        "npc_ocean_spider_ice",
        "npc_ocean_tidehunter",
        "npc_ocean_seledka",
        "npc_ocean_morph_big",
        "npc_ocean_morph_small",
        "npc_ocean_SLARK",
        "npc_ocean_bombardier_melee_1",
        "npc_ocean_bombardier_melee_2",
        "npc_ocean_bombardier_ranged",


        -- darkforest
        "npc_dark_drow",
        "npc_dark_ursa",
        "npc_dark_titan_1",
        "npc_dark_titan_2",
        "npc_dark_pudge",
        "npc_dark_pugna",
        "npc_dark_greevil",
        "npc_dark_shaker_1",
        "npc_dark_shaker_2",
        "npc_dark_shaker_3",
        "npc_dark_treant",
        "npc_dark_treant_summon",

        -- desert
        "npc_desert_nyx_1",
        "npc_desert_nyx_2",
        "npc_desert_nyx_3",
        "npc_desert_viper",
        "npc_desert_lifestealer",
        "npc_desert_huskar",
        "npc_desert_troll",
        "npc_desert_dire_melee",
        "npc_desert_dire_range",
        "npc_desert_dire_siege",


        -- traps
        "npc_trap_arrow",
        "npc_trap_fire",
        "npc_trap_spikes",
        "npc_trap_pendulum",
        "npc_trap_skeleton",
    },
    models = {
        -- ski
        "models/sanya/wearables/sanya_ski.vmdl",

        --mk banana
        "models/props_gameplay/banana_prop_closed_mk.vmdl",
        "models/creeps/roshan_aghanim/roshan_aghanim.vmdl",

        -- tusik papa hide
        "models/heroes/tuskarr/tuskarr_sigil.vmdl",

        -- shrooms
        "models/creeps/lane_creeps/creep_radiant_melee/radiant_melee_mushroom.vmdl",
        "models/creeps/lane_creeps/creep_radiant_ranged/radiant_ranged_mushroom.vmdl",

        -- perdun flowers
        "models/heroes/dawnbreaker/debut/models/flowers/battlemaiden_flower_5.vmdl",
        "models/items/furion/treant_flower_1.vmdl",

        -- axe arcana
        "models/items/axe/ti9_jungle_axe/axe_bare.vmdl",

        -- clash
        "models/items/tiny/scarlet_quarry/scarlet_quarry_03.vmdl",
        "models/items/tiny/lionheart_kings_moving_castle_t2/lionheart_kings_moving_castle_t2.vmdl",
        "models/items/undying/flesh_golem/deathmatch_dominator_golem/deathmatch_dominator_golem.vmdl",

        -- ocean
        "models/creeps/ice_biome/tuskfolk/tuskfolk001b_f.vmdl",

        -- derek wolf
        "models/derek/derek_wolf.vmdl",

        -- george phase 1
        "models/creeps/ice_biome/undeadtusk/undead_tuskskeleton_armor01.vmdl",
    },
    sounds = {
        "soundevents/fake_death.vsndevts",
        "soundevents/sfx.vsndevts",
        "soundevents/items.vsndevts",
        "soundevents/music.vsndevts",
        "soundevents/hlup.vsndevts",
        "soundevents/barrel_click.vsndevts",
        "soundevents/game_sounds_heroes/game_sounds_monkey_king.vsndevts",
        "soundevents/voscripts/game_sounds_vo_monkey_king.vsndevts",
        "soundevents/bosses/bidlo.vsndevts",
        "soundevents/jungle/junglerosh.vsndevts",
        "soundevents/jungle/jungletechies.vsndevts",
        "soundevents/jungle/junglefurion.vsndevts",
        "soundevents/jungle/junglebears.vsndevts",
        "soundevents/jungle/jungleperdun.vsndevts",
        "soundevents/ocean/seledka.vsndevts",
        "soundevents/ocean/arbuz.vsndevts",
        "soundevents/ocean/slark_infester.vsndevts",
        "soundevents/darkforest/dark_drow.vsndevts",
        "soundevents/darkforest/dark_ursa.vsndevts",
        "soundevents/darkforest/dark_shaker.vsndevts",
        "soundevents/desert/desert_dire.vsndevts",
        "soundevents/bosses/ball.vsndevts",
        "soundevents/clash/clash.vsndevts"
    },
    particles = {
        "particles/econ/items/bloodseeker/bloodseeker_crownfall_immortal/bloodseeker_crownfall_immortal_ambient_eyeglow_l.vpcf",
        "particles/econ/items/bloodseeker/bloodseeker_crownfall_immortal/bloodseeker_crownfall_immortal_ambient_eyeglow_r.vpcf",
        "maps/journey_assets/particles/lamp_journey_dire_tintable_f.vpcf",
        "particles/units/heroes/hero_kez/kez_katana_echo_strike_movement_feathers.vpcf",
        "particles/units/heroes/hero_kez/kez_sai_ultimate_crit.vpcf",
        "particles/econ/items/slark/slark_ti6_blade/slark_ti6_pounce_trail_hand_pnt.vpcf",
        "particles/units/heroes/hero_marci/marci_rebound_charge_projectile_streak.vpcf",
        "particles/units/heroes/hero_slark/slark_pounce_trail.vpcf",
        "particles/sanya_towel_dash_trail.vpcf",
        "particles/sanya_towel_dash_splash.vpcf",
        "particles/econ/events/diretide_2020/high_five/high_five_impact_burst.vpcf",
        "particles/econ/events/ti10/high_five/high_five_impact_steam.vpcf",
        "particles/creatures/aghanim/portal_summon_b0a.vpcf",
        "particles/units/heroes/hero_dark_seer/dark_seer_surge.vpcf",
        "particles/sanya_sprint_trail.vpcf",
        "particles/cave_door_open.vpcf",
        "particles/econ/items/winter_wyvern/winter_wyvern_ti7/wyvern_cold_embrace_ti7buff_flakes.vpcf",
        "particles/econ/items/ancient_apparition/aa_blast_ti_5/ancient_apparition_ice_blast_ice_b_ti5.vpcf",
        "particles/econ/items/ancient_apparition/aa_blast_ti_5/ancient_apparition_ice_blast_ice_c_ti5.vpcf",
        "particles/econ/items/ancient_apparition/aa_blast_ti_5/ancient_apparition_ice_blast_explode_ti5.vpcf",
        "particles/final_portal.vpcf",
        "particles/ui_mouseactions/custom_range_finder_cone.vpcf",
        "particles/ui_mouseactions/range_finder_cone.vpcf",
        "particles/ui_mouseactions/range_finder_cone_long.vpcf",
        "particles/warning_circle.vpcf",
        "particles/warning_rope.vpcf",
        "particles/ui_mouseactions/custom_range_finder_cone.vpcf",
        "particles/ui_mouseactions/custom_range_finder_cone_dual.vpcf",

        -- traps
        "particles/units/heroes/hero_dragon_knight/dragon_knight_breathe_fire.vpcf",
        "particles/trap_arrow.vpcf",

        -- towel summon return
        "particles/econ/events/fall_2022/blink/blink_dagger_fall_2022_embers.vpcf",
        "particles/econ/events/fall_2021/agh_aura_fall_2021_parent.vpcf",
        "particles/econ/events/fall_2022/agh/agh_aura_fall2022_lvl2.vpcf",
        "particles/econ/items/antimage_female/monsterhunter_kirin/antimage_manabreak_slow_body_flash.vpcf",

        -- towel root
        "particles/units/heroes/hero_treant/treant_overgrowth_vines_mid.vpcf",
        "particles/econ/items/treant_protector/treant_ti10_immortal_head/treant_ti10_immortal_overgrowth_cast.vpcf",

        -- towel aura's
        "particles/sanya_towel_aura_green.vpcf",
        "particles/sanya_towel_aura_red.vpcf",
        "particles/sanya_towel_aura_blue.vpcf",
        "models/heroes/phantom_assassin_persona/debut/particles/pa_badguy/pa_badguy_bladeimpact_blood_drops.vpcf",

        -- flasks
        "particles/items4_fx/spirit_vessel_damage_blast_burst.vpcf",
        "particles/econ/items/pugna/pugna_ti9_immortal/pugna_ti9_immortal_netherblast_flash_b.vpcf",

        -- quests
        "particles/themed_fx/cny_fireworks_rockets_a.vpcf",
        "particles/themed_fx/cny_fireworks_rockets_b.vpcf",
        "particles/sanya_quest_complete_firework.vpcf",
        "particles/generic_gameplay/generic_has_quest.vpcf",
        "particles/action_remove_smoke.vpcf",

        -- summon explosion
        "particles/sanya_summon_explosion_impact.vpcf",
        "particles/sanya_summon_explosion_impact_alt.vpcf",
        "particles/sanya_summon_explosion_supernova.vpcf",
        "particles/units/heroes/hero_phoenix/phoenix_supernova_death_dust.vpcf",
        "particles/sanya_summon_explosion_ring_outer.vpcf",

        -- summon overpower
        "particles/econ/items/shredder/timber_controlled_burn/timber_controlled_burn_timberchain_ember.vpcf",

        -- jungle
        "particles/econ/events/fall_2022/mjollnir/mjollnir_shield_fall2022.vpcf",
        "particles/techies_poofout.vpcf",
        "particles/shrooms_dig.vpcf",
        "particles/econ/items/axe/axe_cinder/axe_cinder_battle_hunger.vpcf",
        "particles/neutral_fx/ursa_thunderclap.vpcf",
        "particles/roshan_custom_slap_mini.vpcf",
        "particles/roshan_custom_slap.vpcf",
        "particles/units/heroes/hero_lich/lich_ice_age.vpcf",
        "particles/neutral_fx/ogre_magi_frost_armor.vpcf",
        "particles/generic_gameplay/generic_lifesteal.vpcf",
        "particles/units/heroes/hero_pudge/pudge_rot.vpcf",

        -- ocean
        "particles/status_fx/status_effect_poison_venomancer.vpcf",
        "particles/units/heroes/hero_viper/viper_poison_attack_.vpcf",
        "particles/units/heroes/hero_jakiro/jakiro_liquid_ice_projectile.vpcf",
        "particles/units/heroes/hero_jakiro/jakiro_liquid_ice.vpcf",
        "particles/econ/courier/courier_roshan_frost/courier_roshan_frost_ambient.vpcf",
        "particles/units/heroes/hero_jakiro/jakiro_liquid_fire_debuff.vpcf",
        "particles/units/heroes/hero_jakiro/jakiro_liquid_fire_explosion.vpcf",
        "particles/units/heroes/hero_lina/lina_base_attack.vpcf",
        "particles/seledka_puddle_1.vpcf",
        "particles/units/heroes/hero_morphling/morphling_morph_str.vpcf",
        "particles/morph_agi_green.vpcf",
        "particles/units/heroes/hero_morphling/morphling_adaptive_strike_agi_proj.vpcf",
        "particles/units/heroes/hero_morphling/morphling_adaptive_strike.vpcf",
        "status_effect_abaddon_borrowed_time",
        "particles/units/heroes/hero_abaddon/abaddon_borrowed_time.vpcf",
        "particles/slark_attr_passive_death_explosion.vpcf",
        "particles/units/heroes/hero_sandking/sandking_caustic_finale_explode.vpcf",
        "particles/units/heroes/hero_jakiro/jakiro_ice_path.vpcf",
        "particles/units/heroes/hero_jakiro/jakiro_icepath_debuff.vpcf",


        -- dark forest
        "particles/econ/items/drow/drow_arcana/drow_arcana_crit_or_marksmanship_proc.vpcf",
        "particles/status_fx/status_effect_ghost.vpcf",
        "particles/units/heroes/hero_pugna/pugna_decrepify.vpcf",
        "particles/dark_pugna_tp.vpcf",
        "particles/units/heroes/hero_treant/treant_overgrowth_cast.vpcf",
        "particles/units/heroes/hero_treant/treant_overgrowth_vines.vpcf",
        "particles/econ/items/natures_prophet/natures_prophet_weapon_sufferwood/furion_teleport_end_team_sufferwood_model.vpcf",

        -- desert
        "particles/units/heroes/hero_nyx_assassin/nyx_assassin_burrow_exit.vpcf",
        "particles/units/heroes/hero_nyx_assassin/nyx_assassin_burrow.vpcf",
        "particles/units/heroes/hero_huskar/huskar_inner_fire.vpcf",
        "particles/econ/events/fall_2022/blink/blink_dagger_end_fall2022.vpcf",
        "particles/econ/events/fall_2022/blink/blink_dagger_fall_2022_start.vpcf",

        -- clash
        "particles/clash_custom_freeze.vpcf",
        "particles/econ/items/drow/drow_arcana/drow_arcana_status_effect_frost_arrow.vpcf",
        "particles/clash_firework.vpcf",
        "particles/clash_firework_dire.vpcf",
        "particles/econ/world/towers/rock_golem/dire_rock_golem_destruction.vpcf",
        "particles/econ/world/towers/rock_golem/radiant_rock_golem_destruction.vpcf",
        "particles/king_tower_bad_destroy.vpcf",

        -- barrel click
        "particles/units/heroes/hero_bounty_hunter/bounty_hunter_cutpurse.vpcf",
        "particles/dev/library/base_dust_hit.vpcf",
        "particles/barrel_click_countdown.vpcf",

        -- debug
        "particles/sanya_debug_radius_ring.vpcf",

        -- bosses
        "particles/econ/items/monkey_king/arcana/monkey_arcana_cloud_start.vpcf",
        "particles/econ/events/fall_2022/blink/blink_dagger_fall_2022_smokepoof.vpcf",
        "particles/units/heroes/hero_monkey_king/monkey_king_quad_tap_stack.vpcf",
        "particles/units/heroes/hero_monkey_king/monkey_king_quad_tap_debuff.vpcf",

        -- items
        "particles/custom_items/item_fan.vpcf",
        "particles/custom_items/leadlined_grip_impact.vpcf",
        "particles/custom_items/cinder_brand_explosion.vpcf",
        "particles/custom_items/staff_of_madness_aoe.vpcf",
        "particles/items2_fx/mask_of_madness.vpcf",
    },
    particleFolders = {
        "particles/custom_items"
    },
}
