return {
    units = {
        "npc_dota_hero_nevermore",
        "npc_dota_hero_shadow_demon",
        "npc_dota_hero_earthshaker",
        "npc_dota_hero_oracle",

        "npc_dota_hero_sanya_towel_master",
        "npc_dota_hero_sanya_rapper",
        "npc_dota_hero_sanya_logarithmus",
        "npc_dota_hero_sanya",

        "npc_subway_city",
        "npc_subway_to_city",
        "npc_subway_fake",

        "npc_training_dummy",

        "npc_courier_knight",
        "npc_courier_bug",
        "npc_courier_alkash",
        "npc_courier_pivo",
        "npc_courier_chicken",
        "npc_courier_carpet",
        "npc_courier_pudge",
        "npc_courier_hamster",
        "npc_courier_koala",
        "npc_courier_shop",
        "npc_courier_cat",
        "npc_courier_drone",
        "npc_courier_donkeys",
        "npc_courier_bh",
        "npc_courier_chest",
        "npc_courier_skeleton",
        "npc_courier_crocodile",
        "npc_courier_sniffer",
        "npc_courier_smart",
        "npc_courier_roshanchik",

        "npc_courier_roshanchik",
        "npc_courier_bober",
        "npc_courier_rabbit",
        "npc_courier_boar",
        "npc_courier_racoon",
        "npc_courier_parrot",
        "npc_courier_mushroom_1",
        "npc_courier_mushroom_2",
        "npc_courier_mushroom_3",
        "npc_courier_muhomor",
        "npc_courier_plant",
        "npc_courier_octopus_1",
        "npc_courier_octopus_2",
        "npc_courier_purple",
        "npc_courier_sea_horse",
        "npc_courier_turtle",
        "npc_courier_crab",
        "npc_courier_axolotl",
        "npc_courier_navi",
        "npc_courier_cripple_dog",
        "npc_courier_demon",
        "npc_courier_evil_shop",
        "npc_courier_doom",
        "npc_courier_bones",
        "npc_courier_babka_2",
        "npc_courier_blue_frog",
        "npc_courier_pig",

        "npc_courier_aghanim",
        "npc_courier_grandpa",
        "npc_courier_gold_hamster",
        "npc_courier_gold_cat",
        "npc_courier_gold_wizard",
        "npc_courier_blue_zombie",
        "npc_courier_taksa",
        "npc_courier_demon_book",
        "npc_courier_gold_dp",
        "npc_courier_black_wizard",
        "npc_courier_pudge_dog",

        "npc_tormentor",
        "npc_shamanka",
        "npc_gate_troll_uruk",
        "npc_gate_troll_biruk",
        "npc_gate_troll_diruk",
        "npc_guide",
        "npc_creep_bob",
        "npc_creep_rogach",
        "npc_mustache",
        "npc_monkey_king",
        "npc_monkey_king_summon",
        "npc_blue_prince",
        "npc_blue_prince",
        "npc_ogre_magi",
        "npc_ogre_bruiser",
        "npc_brewmaster",
        "npc_rape_victim",
        "npc_predvestnik",
        "npc_mystery",
        "npc_templar_assasin",
        "npc_alchemist",
        "npc_scientist",
        "npc_red",
        "npc_gorilla",
        "npc_cat_barrel",
        "npc_island_guard",
        "npc_island_fiend",
        "npc_island_shadow_demon",
        "npc_bomb_place",
        "npc_bomb",

        "npc_storyteller",
        "npc_leader",
        "npc_xavier",
        "npc_dream",
        "npc_dream_golden",
        "npc_hermit",
        "npc_green",
        "npc_perekup",
        "npc_genius",
        "npc_ghetto_ranged",
        "npc_ghetto_melee",
        "npc_gangster",
        "npc_blue",


        "towel_summon",

        "npc_shooter",
        "mega_sanya",
        "npc_dota_custom_tower_bad",
        "npc_dota_custom_tower_good",
        "npc_dota_custom_king_tower_bad",
        "npc_dota_custom_king_tower_good",

        -- jungle creeps
        "npc_jungle_creep_melee",
        "npc_jungle_creep_range",
        "npc_jungle_axe",
        "npc_jungle_venomancer",
        "npc_jungle_sisipisi",
        "npc_dota_hero_venomancer",
        "npc_dota_hero_axe",
        "npc_dota_hero_razor",
        "npc_dota_hero_antimage",
        "npc_dota_hero_monkey_king",
        "npc_dota_roshan",
        "npc_jungle_roshan",
        "npc_jungle_miniroshan",
        "npc_jungle_techies",
        "npc_dota_hero_techies",
        "npc_dota_hero_furion",
        "npc_dota_hero_meepo",
        "npc_dota_hero_nyx_assassin",


        -- traps
        "npc_trap_arrow",
        "npc_trap_fire",
        "npc_trap_spikes",
        "npc_trap_pendulum",

    },
    models = {
        --mk banana
        "models/props_gameplay/banana_prop_closed_mk.vmdl",
        "models/creeps/roshan_aghanim/roshan_aghanim.vmdl",

        -- shrooms
        "models/creeps/lane_creeps/creep_radiant_melee/radiant_melee_mushroom.vmdl",
        "models/creeps/lane_creeps/creep_radiant_ranged/radiant_ranged_mushroom.vmdl",
    },
    sounds = {
        "soundevents/sfx.vsndevts",
        "soundevents/items.vsndevts",
        "soundevents/music.vsndevts",
        "soundevents/hlup.vsndevts",
        "soundevents/sanya.vsndevts",
        "soundevents/game_sounds_heroes/game_sounds_monkey_king.vsndevts",
        "soundevents/voscripts/game_sounds_vo_monkey_king.vsndevts",
        "soundevents/bosses/bidlo.vsndevts",
        "soundevents/jungle/junglerosh.vsndevts",
        "soundevents/jungle/jungletechies.vsndevts",
        "soundevents/jungle/junglefurion.vsndevts",

    },
    particles = {
        "particles/econ/items/bloodseeker/bloodseeker_crownfall_immortal/bloodseeker_crownfall_immortal_ambient_eyeglow_l.vpcf",
        "particles/econ/items/bloodseeker/bloodseeker_crownfall_immortal/bloodseeker_crownfall_immortal_ambient_eyeglow_r.vpcf",
        "maps/journey_assets/particles/lamp_journey_dire_tintable_f.vpcf",
        "particles/units/heroes/hero_kez/kez_katana_echo_strike_movement_feathers.vpcf",
        "particles/units/heroes/hero_kez/kez_sai_ultimate_crit.vpcf",
        "particles/econ/items/slark/slark_ti6_blade/slark_ti6_pounce_trail_hand_pnt.vpcf",
        "particles/units/heroes/hero_marci/marci_rebound_charge_projectile_streak.vpcf",
        "particles/units/heroes/hero_slark/slark_pounce_trail.vpcf",
        "particles/sanya_towel_dash_trail.vpcf",
        "particles/sanya_towel_dash_splash.vpcf",
        "particles/econ/events/diretide_2020/high_five/high_five_impact_burst.vpcf",
        "particles/econ/events/ti10/high_five/high_five_impact_steam.vpcf",
        "particles/creatures/aghanim/portal_summon_b0a.vpcf",
        "particles/units/heroes/hero_dark_seer/dark_seer_surge.vpcf",
        "particles/sanya_sprint_trail.vpcf",
        "particles/econ/items/winter_wyvern/winter_wyvern_ti7/wyvern_cold_embrace_ti7buff_flakes.vpcf",
        "particles/econ/items/ancient_apparition/aa_blast_ti_5/ancient_apparition_ice_blast_ice_b_ti5.vpcf",
        "particles/econ/items/ancient_apparition/aa_blast_ti_5/ancient_apparition_ice_blast_ice_c_ti5.vpcf",
        "particles/econ/items/ancient_apparition/aa_blast_ti_5/ancient_apparition_ice_blast_explode_ti5.vpcf",
        "particles/ui_mouseactions/range_finder_cone.vpcf",
        "particles/ui_mouseactions/range_finder_cone_long.vpcf",
        "particles/warning_circle.vpcf",

        -- traps
        "particles/units/heroes/hero_dragon_knight/dragon_knight_breathe_fire.vpcf",
        "particles/trap_arrow.vpcf",

        -- towel summon return
        "particles/econ/events/fall_2022/blink/blink_dagger_fall_2022_embers.vpcf",
        "particles/econ/events/fall_2021/agh_aura_fall_2021_parent.vpcf",
        "particles/econ/events/fall_2022/agh/agh_aura_fall2022_lvl2.vpcf",
        "particles/econ/items/antimage_female/monsterhunter_kirin/antimage_manabreak_slow_body_flash.vpcf",

        -- towel root
        "particles/units/heroes/hero_treant/treant_overgrowth_vines_mid.vpcf",
        "particles/econ/items/treant_protector/treant_ti10_immortal_head/treant_ti10_immortal_overgrowth_cast.vpcf",

        -- towel aura's
        "particles/sanya_towel_aura_green.vpcf",
        "particles/sanya_towel_aura_red.vpcf",
        "particles/sanya_towel_aura_blue.vpcf",
        "models/heroes/phantom_assassin_persona/debut/particles/pa_badguy/pa_badguy_bladeimpact_blood_drops.vpcf",

        -- flasks
        "particles/items4_fx/spirit_vessel_damage_blast_burst.vpcf",
        "particles/econ/items/pugna/pugna_ti9_immortal/pugna_ti9_immortal_netherblast_flash_b.vpcf",

        -- quests
        "particles/themed_fx/cny_fireworks_rockets_a.vpcf",
        "particles/themed_fx/cny_fireworks_rockets_b.vpcf",
        "particles/sanya_quest_complete_firework.vpcf",
        "particles/generic_gameplay/generic_has_quest.vpcf",
        "particles/action_remove_smoke.vpcf",

        -- summon explosion
        "particles/sanya_summon_explosion_impact.vpcf",
        "particles/sanya_summon_explosion_impact_alt.vpcf",
        "particles/sanya_summon_explosion_supernova.vpcf",
        "particles/units/heroes/hero_phoenix/phoenix_supernova_death_dust.vpcf",
        "particles/sanya_summon_explosion_ring_outer.vpcf",

        -- summon overpower
        "particles/econ/items/shredder/timber_controlled_burn/timber_controlled_burn_timberchain_ember.vpcf",

        -- jungle
        "particles/econ/events/fall_2022/mjollnir/mjollnir_shield_fall2022.vpcf",
        "particles/techies_poofout.vpcf",
        "particles/shrooms_dig.vpcf",
        -- debug
        "particles/sanya_debug_radius_ring.vpcf",

        --bosses
        "particles/econ/items/monkey_king/arcana/monkey_arcana_cloud_start.vpcf",
        "particles/econ/events/fall_2022/blink/blink_dagger_fall_2022_smokepoof.vpcf",
        "particles/units/heroes/hero_monkey_king/monkey_king_quad_tap_stack.vpcf",
        "particles/units/heroes/hero_monkey_king/monkey_king_quad_tap_debuff.vpcf"
    }
}
